apiVersion: 1

# Provisioned from files; no manual configuration in the UI is needed (or possible: editable=false).
datasources:
  - name: Prometheus
    uid: crm-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: POST
