<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>crm-Crm.Api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Shared/Crm.Shared.Web/Crm.Shared.Web.csproj" />
    <ProjectReference Include="../Modules/Identity/Crm.Modules.Identity.Api/Crm.Modules.Identity.Api.csproj" />
    <ProjectReference Include="../Modules/Sales/Crm.Modules.Sales.Api/Crm.Modules.Sales.Api.csproj" />
    <ProjectReference Include="../Modules/Activities/Crm.Modules.Activities.Api/Crm.Modules.Activities.Api.csproj" />
    <ProjectReference Include="../Modules/Workflows/Crm.Modules.Workflows.Api/Crm.Modules.Workflows.Api.csproj" />
    <ProjectReference Include="../Modules/Marketing/Crm.Modules.Marketing.Api/Crm.Modules.Marketing.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
  </ItemGroup>

</Project>
