#!/usr/bin/env bash
# Generates deploy/.env (random passwords) and deploy/secrets/* (JWT signing key, platform admin password).
# Linux/macOS twin of generate-secrets.ps1. Needs: bash, openssl. Existing files are kept unless FORCE=1.
#
#   PUBLIC_HOSTNAME=crm.company.local PLATFORM_ADMIN_EMAIL=admin@company.local ./deploy/generate-secrets.sh
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="${OUT_DIR:-$here}"
public_hostname="${PUBLIC_HOSTNAME:-crm.example.local}"
admin_email="${PLATFORM_ADMIN_EMAIL:-}"
admin_name="${PLATFORM_ADMIN_NAME:-Platform Admin}"
force="${FORCE:-0}"

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }
[ -f "$here/.env.example" ] || { echo ".env.example not found next to this script" >&2; exit 1; }

umask 077
mkdir -p "$out/secrets"
chmod 700 "$out/secrets"

# 32 alphanumeric characters without look-alikes; no ';', quotes or spaces (they would break connection strings).
secret() { openssl rand -base64 96 | tr -dc 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789' | head -c "${1:-32}"; }

write_file() { # path, content-from-stdin
  local path="$1"
  if [ -e "$path" ] && [ "$force" != "1" ]; then
    echo "Exists, kept (FORCE=1 to overwrite): $path" >&2
    cat >/dev/null
    return 1
  fi
  cat >"$path"
  echo "Wrote $path"
}

declare -A values=(
  [ALLOWED_HOSTS]="$public_hostname"
  [POSTGRES_PASSWORD]="$(secret)"
  [CRM_OWNER_PASSWORD]="$(secret)"
  [CRM_APP_PASSWORD]="$(secret)"
  [CONDUCTOR_DB_PASSWORD]="$(secret)"
  [REDIS_PASSWORD]="$(secret)"
  [PLATFORM_ADMIN_EMAIL]="$admin_email"
  [PLATFORM_ADMIN_NAME]="$admin_name"
)

while IFS= read -r line || [ -n "$line" ]; do
  if [[ "$line" =~ ^([A-Z][A-Z0-9_]*)=(.*)$ ]] && [[ -v "values[${BASH_REMATCH[1]}]" ]]; then
    printf '%s=%s\n' "${BASH_REMATCH[1]}" "${values[${BASH_REMATCH[1]}]}"
  else
    printf '%s\n' "$line"
  fi
done <"$here/.env.example" | write_file "$out/.env" || echo "WARNING: .env was NOT regenerated; existing passwords are unchanged." >&2

# PKCS#1 "RSA PRIVATE KEY" PEM (the API also accepts PKCS#8). World-readable inside the 0700 directory so the container user (uid 1654)
# can read the bind-mounted file; the directory permission is what keeps other host users out.
if [ ! -e "$out/secrets/jwt-signing-key.pem" ] || [ "$force" = "1" ]; then
  openssl genrsa -traditional -out "$out/secrets/jwt-signing-key.pem" 2048 2>/dev/null || openssl genrsa -out "$out/secrets/jwt-signing-key.pem" 2048 2>/dev/null
  chmod 644 "$out/secrets/jwt-signing-key.pem"
  echo "Wrote $out/secrets/jwt-signing-key.pem"
else
  echo "Exists, kept (FORCE=1 to overwrite): $out/secrets/jwt-signing-key.pem" >&2
fi

# AES-256 key (base64, 32 bytes) for webhook secrets at rest (M8B). NEVER regenerated by FORCE=1 (that would make every stored webhook secret unreadable);
# only FORCE_INTEGRATIONS_KEY=1 replaces it (then run the Migrator reencrypt-integration-secrets flow first - see docs/operations/runbook.md section 4).
if [ ! -e "$out/secrets/integrations-encryption-key" ] || [ "${FORCE_INTEGRATIONS_KEY:-0}" = "1" ]; then
  openssl rand -base64 32 | tr -d '\n' >"$out/secrets/integrations-encryption-key"
  chmod 644 "$out/secrets/integrations-encryption-key"
  echo "Wrote $out/secrets/integrations-encryption-key"
else
  echo "Exists, kept (FORCE_INTEGRATIONS_KEY=1 to replace): $out/secrets/integrations-encryption-key" >&2
fi

secret 24 | write_file "$out/secrets/platform-admin-password" || true
# 0600 (owner only): the migrator's create-platform-admin runs with `--user root`, which can read and empty it regardless of the mode.
chmod 600 "$out/secrets/platform-admin-password" 2>/dev/null || true

# Object storage (M8C): MinIO root account, application account (limited to the crm-files bucket) and the static KMS key that encrypts objects at rest.
# BACK UP secrets/minio-kms-key WITH the object data: a data backup without the key is unreadable; the key cannot be rotated in the first release.
printf 'crmroot%s' "$(secret 8)" | write_file "$out/secrets/minio-root-user" || true
secret 32 | write_file "$out/secrets/minio-root-password" || true
printf 'crmfiles%s' "$(secret 12)" | write_file "$out/secrets/minio-app-access-key" || true
secret 32 | write_file "$out/secrets/minio-app-secret-key" || true
printf 'crm-files-key:%s' "$(openssl rand -base64 32)" | write_file "$out/secrets/minio-kms-key" || true
chmod 644 "$out"/secrets/minio-* 2>/dev/null || true

# Observability overlay (docker-compose.observability.yml, C-OPS1): scrape bearer token, Grafana admin password, postgres-exporter role password.
for name in metrics-bearer-token grafana-admin-password pg-monitor-password; do
  secret 40 | write_file "$out/secrets/$name" || true
  chmod 644 "$out/secrets/$name" 2>/dev/null || true
done
chmod 600 "$out/.env" 2>/dev/null || true

cat <<'EOF'

Done. Next steps:
  1. Review deploy/.env (ALLOWED_HOSTS, WEB_BIND/WEB_PORT, PLATFORM_ADMIN_EMAIL, resource limits).
  2. Store .env and secrets/ in your secret vault / encrypted backup. The JWT key and DB passwords are needed to restore.
  3. docker compose -f deploy/docker-compose.prod.yml up -d ; then create the first platform admin:
       docker compose -f deploy/docker-compose.prod.yml run --rm --user root migrator create-platform-admin
     The password is in deploy/secrets/platform-admin-password (mode 0600, read it once). The migrator empties the file after a
     successful create (if it warns that it could not, empty it by hand); the admin must change the password at first login.
  4. TRUSTED_PROXY_CIDR defaults to 127.0.0.1/32 (X-Forwarded-For is NOT trusted). Set it when a reverse proxy/LB is in front (see .env.example).
EOF
