<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Crm.Modules.Sales.Contracts/Crm.Modules.Sales.Contracts.csproj" />
    <ProjectReference Include="../Crm.Modules.Sales.Domain/Crm.Modules.Sales.Domain.csproj" />
    <ProjectReference Include="../../Identity/Crm.Modules.Identity.Contracts/Crm.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/Crm.Shared.Kernel/Crm.Shared.Kernel.csproj" />
    <ProjectReference Include="../../../Shared/Crm.Shared.Contracts/Crm.Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

</Project>
