<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Crm.Modules.Workflows.Application/Crm.Modules.Workflows.Application.csproj" />
    <ProjectReference Include="../Crm.Modules.Workflows.Contracts/Crm.Modules.Workflows.Contracts.csproj" />
    <ProjectReference Include="../Crm.Modules.Workflows.Infrastructure/Crm.Modules.Workflows.Infrastructure.csproj" />
    <ProjectReference Include="../../../Shared/Crm.Shared.Web/Crm.Shared.Web.csproj" />
    <ProjectReference Include="../../../Shared/Crm.Shared.Infrastructure/Crm.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
